// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1727.REX;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogAccelerometer;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.MotorSafety;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.VictorSP;

import com.ctre.CANTalon;


    









// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainleftDrive;
    public static SpeedController drivetrainrightDrive;
    public static RobotDrive drivetraindrive;
    public static SpeedController flywheelflywheel;
    public static Encoder flywheelflywheelSpeed;
    public static DoubleSolenoid gearHopperHopperRelease;
    public static DoubleSolenoid gearCatcher;
   // public static AnalogGyro fRPSyawSensor;
    public static AnalogAccelerometer fRPSxAccelSensor;
    public static Encoder fRPSrightDriveSensor;
    public static Encoder fRPSleftDriveSensor;
    public static AnalogAccelerometer fRPSyAccelSensor;
    public static SpeedController climberwinchMotor;
    public static CANTalon talonFlywheelSpeed;
    public static SpeedController flywheelIntake;
    public static Compressor gearCompressor;
    public static Relay basketIntake;
    public static Relay ledSwitch;
    public static DoubleSolenoid climberBreak;
    public static ADXRS450_Gyro autonGyro;
    public static Ultrasonic ultrasonic;
    public static AnalogInput sonar;
    //public static Encoder autonRightDriveSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainleftDrive = new Spark(1);
        
        LiveWindow.addActuator("Drivetrain", "leftDrive", (Spark) drivetrainleftDrive);
        
        drivetrainrightDrive = new Spark(0);
        LiveWindow.addActuator("Drivetrain", "rightDrive", (Spark) drivetrainrightDrive);
        drivetrainrightDrive.setInverted(true);
        drivetraindrive = new RobotDrive(drivetrainleftDrive, drivetrainrightDrive);
        
        
        
        drivetraindrive.setSafetyEnabled(true);
        
        drivetraindrive.setExpiration(2);//MotorSafety.DEFAULT_SAFETY_EXPIRATION
        drivetraindrive.setMaxOutput(1.0);
        drivetraindrive.setSensitivity(RobotDrive.kDefaultSensitivity);
        
        // drivetraindrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
       
        
        sonar = new AnalogInput(0);
        LiveWindow.addActuator("Drivetrain", "sonar",(AnalogInput)sonar);
        //drivetraindrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        //drivetraindrive.setInvertedMotor(RobotDrive.MotorType., isInverted);
        
        
        flywheelIntake = new Victor(2);
        flywheelIntake.setInverted(true);
        LiveWindow.addActuator("Intake", "flywheelIntake", (Victor) flywheelIntake);
        
        basketIntake = new Relay(3);
        LiveWindow.addActuator("Intake", "basketIntake", (Relay)basketIntake);
        ledSwitch = new Relay(0	 	);
        
        
        //flywheelflywheel = new TalonSRX(2);
        //LiveWindow.addActuator("Flywheel", "flywheel", (TalonSRX) flywheelflywheel);
        
        talonFlywheelSpeed = new CANTalon(1);
        talonFlywheelSpeed.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
        talonFlywheelSpeed.reverseSensor(true);
        talonFlywheelSpeed.reverseOutput(true);
        talonFlywheelSpeed.setProfile(0);
        
        
        /*flywheelflywheelSpeed = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Flywheel", "flywheelSpeed", flywheelflywheelSpeed);
        flywheelflywheelSpeed.setDistancePerPulse(1.0);
        flywheelflywheelSpeed.setPIDSourceType(PIDSourceType.kRate);*/
        gearHopperHopperRelease = new DoubleSolenoid(1, 0);
        LiveWindow.addActuator("GearHopper", "HopperRelease", (DoubleSolenoid)gearHopperHopperRelease);
        climberBreak = new DoubleSolenoid(6,7);
        LiveWindow.addActuator("Climber", "climberBreak", (DoubleSolenoid)climberBreak);
        gearCompressor = new Compressor(0);
        LiveWindow.addActuator("GearHopper", "gearCompressor",(Compressor)gearCompressor);
        
        gearCatcher = new DoubleSolenoid(3,2);
        LiveWindow.addActuator("GearHopper", "gearCatcher", (DoubleSolenoid)gearCatcher);
        
        autonGyro = new ADXRS450_Gyro(SPI.Port.kOnboardCS0);
        LiveWindow.addActuator("Drivetrain", "autonGyro", (ADXRS450_Gyro)autonGyro);
     //   fRPSyawSensor = new AnalogGyro(0);
       // LiveWindow.addSensor("FRPS", "yawSensor", fRPSyawSensor);
        //fRPSyawSensor.setSensitivity(0.007);
        fRPSxAccelSensor = new AnalogAccelerometer(1);
        LiveWindow.addSensor("FRPS", "xAccelSensor", fRPSxAccelSensor);
        fRPSxAccelSensor.setSensitivity(0.0);
        fRPSxAccelSensor.setZero(2.5);
        fRPSrightDriveSensor = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("FRPS", "rightDriveSensor", fRPSrightDriveSensor);
        fRPSrightDriveSensor.setDistancePerPulse(1.0);
        fRPSrightDriveSensor.setPIDSourceType(PIDSourceType.kRate);
        fRPSleftDriveSensor = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("FRPS", "leftDriveSensor", fRPSleftDriveSensor);
        fRPSleftDriveSensor.setDistancePerPulse(1.0);
        fRPSleftDriveSensor.setPIDSourceType(PIDSourceType.kRate);
       fRPSleftDriveSensor.setReverseDirection(true);
        fRPSyAccelSensor = new AnalogAccelerometer(2);
        LiveWindow.addSensor("FRPS", "yAccelSensor", fRPSyAccelSensor);
        fRPSyAccelSensor.setSensitivity(0.0);
        fRPSyAccelSensor.setZero(2.5);
		//climberwinchMotor = new Victor(2);
		climberwinchMotor = new VictorSP(3);
		climberwinchMotor.setInverted(true);
        LiveWindow.addActuator("Climber", "winchMotor", (VictorSP) climberwinchMotor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
